lastuploadedfiles:
    pattern:      /lastuploadedfiles/
    defaults:     { _controller: SpookyIslandUploadBundle:Application:lastUploadedFiles }

deletetrack:
    pattern:      /deletetrack/
    defaults:     { _controller: SpookyIslandUploadBundle:Application:delete }
    
findtrack:
    pattern:      /findtrack/
    defaults:     { _controller: SpookyIslandUploadBundle:Application:find }
    
downloadtrack:
    pattern:      /downloadtrack/
    defaults:     { _controller: SpookyIslandUploadBundle:Application:download }
